# Generated by Django 4.1.3 on 2023-02-08 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_bio_alter_profile_user'),
        ('web', '0007_alter_job_response_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Название организации'),
        ),
    ]
