# Generated by Django 4.1.3 on 2023-02-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_job_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.CharField(max_length=50, verbose_name='Название организации'),
        ),
    ]
