# Generated by Django 4.1.3 on 2023-02-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('Пользователь', 'Пользователь'), ('Детский', 'Детский'), ('Работодатель', 'Работодатель')], default='Пользователь', max_length=50, verbose_name='Тип аккаунта'),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Возраст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=0, max_length=50, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(default=0, max_length=50, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
