# Generated by Django 4.1.3 on 2023-02-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_bio_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employer',
            field=models.CharField(max_length=50, null=True, verbose_name='Название организации'),
        ),
    ]
