# Generated by Django 4.1.3 on 2023-02-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия'),
        ),
    ]
