# Generated by Django 4.1.3 on 2023-02-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='employer',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Название организации'),
        ),
    ]
