# Generated by Django 4.1.3 on 2023-02-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='employer',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_2.png', upload_to='profile_pics'),
        ),
    ]
