# Generated by Django 4.1.3 on 2023-02-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_3.png', upload_to='profile_pics'),
        ),
    ]
