# Generated by Django 4.1.3 on 2023-02-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contacts',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_contacts',
            field=models.CharField(choices=[('Пользователь', 'Пользователь'), ('Детский', 'Детский'), ('Работодатель', 'Работодатель')], default='Скрывать', max_length=50, verbose_name='Отображение контактов'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_email',
            field=models.CharField(choices=[('Пользователь', 'Пользователь'), ('Детский', 'Детский'), ('Работодатель', 'Работодатель')], default='Скрывать', max_length=50, verbose_name='Отображение почты'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_3.png', upload_to='profile_pics'),
        ),
    ]
