# Generated by Django 4.1.3 on 2023-02-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_profile_contacts_profile_show_contacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('Отображать', 'Отображать'), ('Скрывать', 'Скрывать')], default='Пользователь', max_length=50, verbose_name='Тип аккаунта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contacts',
            field=models.CharField(max_length=50, null=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_4.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_contacts',
            field=models.CharField(choices=[('Отображать', 'Отображать'), ('Скрывать', 'Скрывать')], default='Скрывать', max_length=50, verbose_name='Отображение контактов'),
        ),
    ]
