# Generated by Django 4.1.3 on 2023-02-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_profile_contacts_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('Пользователь', 'Пользователь'), ('Детский', 'Детский'), ('Работодатель', 'Работодатель')], default='Пользователь', max_length=50, verbose_name='Тип аккаунта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_1.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_email',
            field=models.CharField(choices=[('Отображать', 'Отображать'), ('Скрывать', 'Скрывать')], default='Скрывать', max_length=50, verbose_name='Отображение почты'),
        ),
    ]
