# Generated by Django 4.1.3 on 2023-02-22 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0029_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_employment', models.CharField(choices=[('Полная занятость', 'Полная занятость'), ('Частичная занятость', 'Частичная занятость'), ('Проектная работа', 'Проектная работа'), ('Стажировка', 'Стажировка')], max_length=50, verbose_name='Тип занятости')),
                ('schedule', models.CharField(choices=[('Полный день', 'Полный день'), ('Вахтовый метод', 'Вахтовый метод'), ('Сменный график', 'Сменный график'), ('Удаленная работа', 'Удаленная работа'), ('Гибкий график', 'Гибкий график')], max_length=50, verbose_name='График работы')),
                ('experience', models.CharField(choices=[('Не важно', 'Не важно'), ('До 1 года', 'До 1 года'), ('От 1 года', 'От 1 года'), ('От 2 лет', 'От 2 лет'), ('Более 5 лет', 'Более 5 лет')], max_length=50, verbose_name='Опыт работы')),
                ('special_conditions', models.CharField(choices=[('Проблемы со зрением', 'Проблемы со зрением'), ('Проблемы со слухом', 'Проблемы со слухом'), ('Проблемы c речью', 'Проблемы c речью'), ('Нарушения опорно-двигательного аппарата', 'Нарушения опорно-двигательного аппарата'), ('Ментальные нарушения', 'Ментальные нарушения'), ('Другое', 'Другое')], max_length=50, verbose_name='Особые условия')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='Ваше описание')),
                ('link', models.CharField(max_length=200, verbose_name='Ссылка на портфолио')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
    ]
