# Generated by Django 4.1.3 on 2023-02-23 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0030_user_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_4.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='user_portfolio',
            name='experience',
            field=models.CharField(choices=[('Отсутствует', 'Отсутствует'), ('До 1 года', 'До 1 года'), ('От 1 года', 'От 1 года'), ('От 2 лет', 'От 2 лет'), ('Более 5 лет', 'Более 5 лет')], max_length=50, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='user_portfolio',
            name='special_conditions',
            field=models.CharField(choices=[('Проблемы со зрением', 'Проблемы со зрением'), ('Проблемы со слухом', 'Проблемы со слухом'), ('Проблемы c речью', 'Проблемы c речью'), ('Нарушения опорно-двигательного аппарата', 'Нарушения опорно-двигательного аппарата'), ('Ментальные нарушения', 'Ментальные нарушения'), ('Другое', 'Другое'), ('Отсутствуют', 'Отсутствуют')], max_length=50, verbose_name='Особые условия'),
        ),
        migrations.AlterField(
            model_name='user_portfolio',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
