# Generated by Django 4.1.3 on 2023-02-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_profile_image_alter_user_portfolio_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_portfolio',
            name='about',
            field=models.TextField(max_length=500, verbose_name='Ваше описание'),
        ),
        migrations.AlterField(
            model_name='user_portfolio',
            name='link',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка на портфолио'),
        ),
    ]
