# Generated by Django 4.1.3 on 2023-02-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_user_portfolio_about_alter_user_portfolio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_portfolio',
            name='education',
            field=models.TextField(default=0, max_length=500, verbose_name='Ваше описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_portfolio',
            name='languages',
            field=models.TextField(default=0, max_length=500, verbose_name='Языки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_portfolio',
            name='work_experience',
            field=models.TextField(default=0, max_length=500, verbose_name='Опыт работы'),
            preserve_default=False,
        ),
    ]
