# Generated by Django 4.1.3 on 2023-02-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_user_portfolio_education_user_portfolio_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_portfolio',
            name='experience',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_1.png', upload_to='profile_pics'),
        ),
    ]
