# Generated by Django 4.1.3 on 2023-02-24 03:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0037_alter_profile_image_children_achievements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Children_achievements',
            new_name='Children_achievement',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_2.png', upload_to='profile_pics'),
        ),
    ]
