# Generated by Django 4.1.3 on 2023-02-24 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_rename_children_achievements_children_achievement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='children_achievement',
            options={'verbose_name': 'Достижения', 'verbose_name_plural': 'Достижения'},
        ),
    ]
