# Generated by Django 4.1.3 on 2023-02-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_children_achievement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children_achievement',
            name='image',
            field=models.ImageField(upload_to='achievements_pics', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_1.png', upload_to='profile_pics'),
        ),
    ]
