# Generated by Django 4.1.3 on 2023-02-05 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Категория фильтра')),
            ],
            options={
                'verbose_name': 'Категории фильтров',
                'verbose_name_plural': 'Категории фильтров',
            },
        ),
        migrations.CreateModel(
            name='Job_subfilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=50, verbose_name='Элемент фильтра')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.job_filter', verbose_name='Категория фильтра')),
            ],
        ),
    ]
