# Generated by Django 4.1.3 on 2023-02-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название вакансии')),
                ('employer', models.CharField(max_length=50, verbose_name='Название организации')),
                ('min_salary', models.IntegerField(verbose_name='ЗП от')),
                ('max_salary', models.IntegerField(verbose_name='ЗП до')),
                ('date', models.DateField(blank=True, verbose_name='Дата')),
                ('type_of_employment', models.CharField(choices=[('Полная занятость', 'Полная занятость'), ('Частичная занятость', 'Частичная занятость')], max_length=50, verbose_name='Тип занятости')),
                ('schedule', models.CharField(max_length=50, verbose_name='График работы')),
                ('experience', models.CharField(max_length=50, verbose_name='Опыт работы')),
                ('special_conditions', models.CharField(max_length=50, verbose_name='Особые условия')),
            ],
            options={
                'verbose_name': 'Вакансии',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.RemoveField(
            model_name='job_subfilter',
            name='title',
        ),
        migrations.DeleteModel(
            name='Job_filter',
        ),
        migrations.DeleteModel(
            name='Job_subfilter',
        ),
    ]
