# Generated by Django 4.1.3 on 2023-02-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_job_remove_job_subfilter_title_delete_job_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default=0, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default=0, upload_to='job_pics'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('Не важно', 'Не важно'), ('До 1 года', 'До 1 года'), ('От 1 года', 'От 1 года'), ('От 2 лет', 'От 2 лет'), ('Более 5 лет', 'Более 5 лет')], max_length=50, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='job',
            name='schedule',
            field=models.CharField(choices=[('Полный день', 'Полный день'), ('Вахтовый метод', 'Вахтовый метод'), ('Сменный график', 'Сменный график'), ('Удаленная работа', 'Удаленная работа'), ('Гибкий график', 'Гибкий график')], max_length=50, verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='job',
            name='special_conditions',
            field=models.CharField(choices=[('Проблемы со зрением', 'Проблемы со зрением'), ('Проблемы со слухом', 'Проблемы со слухом'), ('Проблемы c речью', 'Проблемы c речью'), ('Нарушения опорно-двигательного аппарата', 'Нарушения опорно-двигательного аппарата'), ('Ментальные нарушения', 'Ментальные нарушения'), ('Другое', 'Другое')], max_length=50, verbose_name='Особые условия'),
        ),
        migrations.AlterField(
            model_name='job',
            name='type_of_employment',
            field=models.CharField(choices=[('Полная занятость', 'Полная занятость'), ('Частичная занятость', 'Частичная занятость'), ('Проектная работа', 'Проектная работа'), ('Стажировка', 'Стажировка')], max_length=50, verbose_name='Тип занятости'),
        ),
    ]
