# Generated by Django 4.1.3 on 2023-02-06 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0006_remove_job_response_user_job_response_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_response',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_response_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
