# Generated by Django 4.1.3 on 2023-02-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_job_employer_alter_job_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
    ]
