# Generated by Django 4.1.3 on 2023-02-10 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0015_job_response_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание')),
                ('experience', models.CharField(choices=[('Не важно', 'Не важно'), ('До 1 года', 'До 1 года'), ('От 1 года', 'От 1 года'), ('От 2 лет', 'От 2 лет'), ('Более 5 лет', 'Более 5 лет')], max_length=50, verbose_name='Опыт работы')),
                ('special_conditions', models.CharField(choices=[('Проблемы со зрением', 'Проблемы со зрением'), ('Проблемы со слухом', 'Проблемы со слухом'), ('Проблемы c речью', 'Проблемы c речью'), ('Нарушения опорно-двигательного аппарата', 'Нарушения опорно-двигательного аппарата'), ('Ментальные нарушения', 'Ментальные нарушения'), ('Другое', 'Другое')], max_length=50, verbose_name='Готов работать с')),
                ('employment', models.CharField(choices=[('Только в будние дни', 'Только в будние дни'), ('Только в выходные дни', 'Только в выходные дни'), ('Любые дни', 'Любые дни')], max_length=50, verbose_name='Занятость')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialist_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Специалисты',
                'verbose_name_plural': 'Специалисты',
            },
        ),
    ]
