# Generated by Django 4.1.3 on 2023-02-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_specialist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='employment',
        ),
        migrations.AddField(
            model_name='specialist',
            name='type_of_employment',
            field=models.CharField(choices=[('Только в будние дни', 'Только в будние дни'), ('Только в выходные дни', 'Только в выходные дни'), ('Любые дни', 'Любые дни')], default=0, max_length=50, verbose_name='Тип занятости'),
            preserve_default=False,
        ),
    ]
