# Generated by Django 4.1.3 on 2023-02-11 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_remove_specialist_employment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Дата'),
        ),
    ]
