# Generated by Django 4.1.3 on 2023-02-13 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0018_specialist_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('Специалисты', 'Специалисты'), ('Специалисты', 'Специалисты'), ('Нуждается в помощи', 'Нуждается в помощи'), ('Мероприятия', 'Мероприятия'), ('Секции', 'Секции')], max_length=50, verbose_name='Название услуги')),
                ('service_id', models.IntegerField(verbose_name='ID услуги')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
    ]
