# Generated by Django 4.1.3 on 2023-02-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_alter_favorite_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='service_name',
            field=models.CharField(choices=[('Специалисты', 'Специалисты'), ('Волонтерство', 'Волонтерство'), ('Нуждается в помощи', 'Нуждается в помощи'), ('Мероприятия', 'Мероприятия'), ('Секции', 'Секции')], max_length=50, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название вакансии'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='experience',
            field=models.CharField(choices=[('До 1 года', 'До 1 года'), ('От 1 года', 'От 1 года'), ('От 2 лет', 'От 2 лет'), ('Более 5 лет', 'Более 5 лет')], max_length=50, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название вакансии'),
        ),
    ]
