# Generated by Django 4.1.3 on 2023-02-15 11:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0022_alter_favorite_service_name_alter_job_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название услуги'),
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Дата')),
                ('type_of_employment', models.CharField(choices=[('Только в будние дни', 'Только в будние дни'), ('Только в выходные дни', 'Только в выходные дни'), ('Любые дни', 'Любые дни')], max_length=50, verbose_name='Тип занятости')),
                ('work_with', models.CharField(choices=[('Ребенку', 'Ребенку'), ('Взрослому', 'Взрослому'), ('Пожилому', 'Пожилому'), ('Всем', 'Всем')], max_length=50, verbose_name='Готов помочь')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Волонтеры',
                'verbose_name_plural': 'Волонтеры',
            },
        ),
    ]
