# Generated by Django 4.0.6 on 2023-02-17 02:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0023_alter_specialist_title_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название услуги волонтера'),
        ),
        migrations.CreateModel(
            name='NeedHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название услуги волонтера')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Дата')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='needhelp_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Волонтеры',
                'verbose_name_plural': 'Волонтеры',
            },
        ),
    ]
