# Generated by Django 4.0.6 on 2023-02-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_alter_specialist_title_alter_volunteer_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='needhelp',
            name='support_type',
            field=models.CharField(choices=[('Финансы', 'Финансы'), ('Услуга', 'Услуга'), ('Прочее', 'Прочее')], default=0, max_length=50, verbose_name='Способ помочь'),
            preserve_default=False,
        ),
    ]
