# Generated by Django 4.1.3 on 2023-02-17 07:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0025_needhelp_support_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название услуги волонтера')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Дата')),
                ('event_location', models.CharField(max_length=50, verbose_name='Адрес мероприятия')),
                ('event_date', models.DateField(verbose_name='Дата мероприятия')),
                ('event_time', models.TimeField(verbose_name='Время мероприятия')),
                ('event_theme', models.CharField(choices=[('Спорт', 'Спорт'), ('Цирк', 'Цирк'), ('Городские события', 'Городские события'), ('Игры и квесты', 'Игры и квесты'), ('Театры', 'Театры'), ('Концерты', 'Концерты'), ('Музеи и галереи', 'Музеи и галереи'), ('Экскурсии ', 'Экскурсии '), ('Обучение ', 'Обучение '), ('Творчество', 'Творчество')], max_length=50, verbose_name='Способ помочь')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Секции',
                'verbose_name_plural': 'Секции',
            },
        ),
    ]
