# Generated by Django 4.1.3 on 2023-02-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_remove_section_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='display_status',
            field=models.CharField(choices=[('Отображать', 'Отображать'), ('Скрывать', 'Скрывать')], default=0, max_length=50, verbose_name='Статус отображения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название мероприятия'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название секции'),
        ),
    ]
