# Generated by Django 4.1.3 on 2023-02-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_alter_event_display_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='needhelp',
            options={'verbose_name': 'Нуждаются в помощи', 'verbose_name_plural': 'Нуждаются в помощи'},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='service_name',
            field=models.CharField(choices=[('Специалисты', 'Специалисты'), ('Волонтерство', 'Волонтерство'), ('Нуждаются в помощи', 'Нуждаются в помощи'), ('Мероприятия', 'Мероприятия'), ('Секции', 'Секции')], max_length=50, verbose_name='Название услуги'),
        ),
    ]
