# Generated by Django 4.1.3 on 2023-02-18 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_alter_needhelp_options_alter_favorite_service_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категории полезной информации',
                'verbose_name_plural': 'Категории полезной информации',
            },
        ),
        migrations.CreateModel(
            name='InfoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Название')),
                ('File', models.FileField(null=True, upload_to='info/file/', verbose_name='Фаил')),
                ('Visibility', models.CharField(choices=[('Отображать', 'Отображать'), ('Не отображать', 'Не отображать')], default='Отображать', max_length=50, verbose_name='Отображение')),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infocategory_category', to='web.infocategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуга',
            },
        ),
    ]
