# Generated by Django 4.1.3 on 2023-02-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(max_length=10000, verbose_name='Описание'),
        ),
    ]
